var Name = "Alishba";
console.log(Name == "Alishba"); //true
console.log(Name == "Muniba"); //false
var num = 5;
console.log(num == 6); //false
console.log(num == 5); //true
var favGame = "Pubg";
console.log(favGame == "ludo"); //false
console.log(favGame == "Pubg"); //true
var bestFriend = "Muniba";
console.log(bestFriend == "Muniba"); //true
console.log(bestFriend == "hoor"); //false
var favDish = "biryani";
console.log(favDish == "biryani"); //true
console.log(favDish == "karahi"); //false
